/********************************************************************
 *                 WARNING - DO NOT EDIT THIS FILE                  *
 * This file is automatially generated by the energyAware Designer. *
 * Any changes to this file will be overwritten if the project      *
 * files are generated again by the eADesigner.                     *
 ********************************************************************/

#include "em_adc.h"

#ifndef ADC0_H
#define ADC0_H
/***************************************************************************//**
 * @brief
 *   Initializes ADC0.
 * @note
 *   This function was autogenerated by energyAware Designer.
 ******************************************************************************/
void ADC0_setup(void);
#endif

