/********************************************************************
 *                 WARNING - DO NOT EDIT THIS FILE                  *
 * This file is automatially generated by the energyAware Designer. *
 * Any changes to this file will be overwritten if the project      *
 * files are generated again by the eADesigner.                     *
 ********************************************************************/

#include "em_usart.h"

#ifndef USART1_H
#define USART1_H
/***************************************************************************//**
 * @brief
 *   Initializes USART1.
 * @note
 *   This function was autogenerated by energyAware Designer.
 ******************************************************************************/
void
USART1_setup(void);
#endif

