/********************************************************************
 *                 WARNING - DO NOT EDIT THIS FILE                  *
 * This file is automatially generated by the energyAware Designer. *
 * Any changes to this file will be overwritten if the project      *
 * files are generated again by the eADesigner.                     *
 ********************************************************************/

#include "autogen_adc0.h"
#include "autogen_hfxo.h"
#include "autogen_lfxo.h"
#include "autogen_usart1.h"
#include "autogen_usart2.h"

void eADesigner_Init(void);
